### PR TITLE
Make example data easier to understand

### PR DESCRIPTION
**Pull request by okin**

### CODE REVIEW

**Comment by godspeed-you** [comment]
Hi - could you please rebase? The code should be adjusted meanwhile. I also fixed another place of inconsistent output examples.

**Comment by okin** [comment]
@godspeed-you the changes have been rebased

**Comment by godspeed-you** [comment]
@okin Is there a reason, why you want to change this example in the text? As far as I can see, the example code is now consistent with the text.

**Comment by okin** [comment]
@godspeed-you for West it is hard for a user to differentiate what value stands for used places and which for the total capacity because both have the same value.
By switching this to East it is easier for users to understand what the values in the examples stand for what since they use different values.

I'll update the MR description to better reflect the goal of this in line with the new document.

**Comment by sebkir** [comment]
Though I see what you are aiming at, I have to say that the example here is totally arbitrary. The definition of what - in the context of this example - counts as "total capacity" / "_slots in section", comes later in the example, when the for loop reads the list. I see no added value in changing the text here and will close the PR.

**Pull request closed without merging**
